### PR TITLE
Fix findMap.html use of single-quotes

### PR DESCRIPTION
**Pull request by corrspt**
Looks weird using single-quotes in the code highlight

### CODE REVIEW

**Comment by rbygrave** [comment]
Yeah cool - merging ..

**Comment by corrspt** [comment]
Thanks Rob
Although still looks funny :(
The comments inside `/**/` are not getting properly rendered

If you find the opportunity to add a `how to build` the website from source, in the my next PR's I'll look at that visual side as well :)

**Comment by rbygrave** [comment]
Pushed instructions for building the website to https://github.com/ebean-orm/website-source/blob/master/README.md

Hopefully those are reasonable to follow.  Thanks for your efforts with updating the docs ... much appreciated. 

Cheers, Rob.

**Comment by corrspt** [comment]
Ah, thanks a lot Rob :)

**Pull request merged**
