### PR TITLE
Added Quick Start and other pages

### PR DESCRIPTION
**Pull request by mrock42**
Added Quick Start, Enhancement Docs, and reworked releases page.

A main goal for me was to keep the versions on the website up to date.  This is being done through REST call to search.maven.org and using a json to jsonp website to enable the cross site ajax call.

Also, the quick start assumes that there is an apidocs folder holding the javadocs.  suggested commands:
cd ${avaje-ebeanorm}
mvn javadoc:javadoc
cp -R target/site/apidocs ${ebean-orm-site}/apidocs

### CODE REVIEW

**Comment by mrock42** [comment]
I was a little unhappy with the ajax call per page load.  So now, I changed the code to store the versions pulled from search.maven.org in session storage.  I then moved that logic into the main.html template and so it will run on every page.  So now, every page can include <span class="${artifactid}-version}></span> and on page load, it will be filled with the most current version.

**Comment by mrock42** [comment]
I reworked the documentation to be a single page with a scrollspy navbar sidebar.  I also am assuming that the apidocs will be added to github as I noted in my first comment... so I added an "ApiDocs" nav link on the main toolbar.  To help with keeping the main toolbar shorter, I renamed the "Documentation" nav link to "Docs". 

Next, I plan on trying to merge in text from the old pdf documentation, and any other sources I can find.

**Comment by mrock42** [comment]
I merged in documentation from old pdf, old website, and current javadocs.  I also fixed the scrollspy and links to scroll properly with the main site fixed header.

**Comment by mrock42** [comment]
BTW, these were the the last of the changes I plan to make in the near term.

**Comment by mrock42** [comment]
Hmmm.. Actually, I see some trivial typos that affect formatting in some places.  I plan on fixing and doing another commit tomorrow.

**Comment by mrock42** [comment]
I fixed some typos, but then added documentation to the areas under construction.  The document in general should be reviewed, but searching for "under construction" should give to areas where I created documentation without a strong knowledge of that topic.   I hope to do another round of edits in a couple weeks. My aim was to build content quickly, so there are plenty of parts that are redundant or can be reworded/restructured.  I feel more content still needs to be built up, and then after that, I plan on editing so the document reads better from top to bottom, like a book.  I want to add many more references to the apidocs since there is good documentation there, and to the code in the test classes since a lot of them serve as great examples.

**Comment by rbygrave** [comment]
Great work - thanks !!  Documentation always needs work but this is a great help.  

Cheers, Rob.

**Comment by rbygrave** [comment]
Ok, I have pushed all that - excellent work.  Thanks again.

**Comment by mrock42** [comment]
You're welcome. And Thank You for all your work over the years.

**Pull request merged**
