### PR TITLE
Add documenation to findEach

### PR DESCRIPTION
**Pull request by corrspt**
Copied the documentation from the `Javadoc` to the `findEac.h` page, added the links to the corresponding methods and made the code highlighted

### CODE REVIEW

**Comment by corrspt** [comment]
Hi Rob,

I just copy pasted the Javadoc, added links where required and added syntax highlighting. And made some small adjustments (better than having an empty page I hope :) )

EDIT: I don't know how to build the site, so i Hope that everything is ok :)

**Comment by rbygrave** [comment]
Yup, that is great.  I'll merge and check it etc.

**Comment by rbygrave** [comment]
Ok, that is live now. Cheers !!!

**Comment by corrspt** [comment]
Great :) As I get the chance, I'll try to do the same with other pages that have missing content (if I can add content other than the Javadoc, I'll also do that)

Many thanks for your work on Ebean, @rbygrave

**Pull request merged**
